/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalTerminiRouteImport } from './routes/legal.termini'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRegistroCorrispettiviRouteImport } from './routes/_authenticated/registro-corrispettivi'
import { Route as AuthenticatedPlatformsRouteImport } from './routes/_authenticated/platforms'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedGalleriaFotoRouteImport } from './routes/_authenticated/galleria-foto'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedAuditLogRouteImport } from './routes/_authenticated/audit-log'
import { Route as AuthenticatedAnnunciRouteImport } from './routes/_authenticated/annunci'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTerminiRoute = LegalTerminiRouteImport.update({
  id: '/legal/termini',
  path: '/legal/termini',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRegistroCorrispettiviRoute =
  AuthenticatedRegistroCorrispettiviRouteImport.update({
    id: '/registro-corrispettivi',
    path: '/registro-corrispettivi',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformsRoute = AuthenticatedPlatformsRouteImport.update({
  id: '/platforms',
  path: '/platforms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGalleriaFotoRoute =
  AuthenticatedGalleriaFotoRouteImport.update({
    id: '/galleria-foto',
    path: '/galleria-foto',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditLogRoute = AuthenticatedAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnnunciRoute = AuthenticatedAnnunciRouteImport.update({
  id: '/annunci',
  path: '/annunci',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/annunci': typeof AuthenticatedAnnunciRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/galleria-foto': typeof AuthenticatedGalleriaFotoRoute
  '/home': typeof AuthenticatedHomeRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/platforms': typeof AuthenticatedPlatformsRoute
  '/registro-corrispettivi': typeof AuthenticatedRegistroCorrispettiviRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/legal/termini': typeof LegalTerminiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/annunci': typeof AuthenticatedAnnunciRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/galleria-foto': typeof AuthenticatedGalleriaFotoRoute
  '/home': typeof AuthenticatedHomeRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/platforms': typeof AuthenticatedPlatformsRoute
  '/registro-corrispettivi': typeof AuthenticatedRegistroCorrispettiviRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/legal/termini': typeof LegalTerminiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/annunci': typeof AuthenticatedAnnunciRoute
  '/_authenticated/audit-log': typeof AuthenticatedAuditLogRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/galleria-foto': typeof AuthenticatedGalleriaFotoRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/platforms': typeof AuthenticatedPlatformsRoute
  '/_authenticated/registro-corrispettivi': typeof AuthenticatedRegistroCorrispettiviRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/legal/termini': typeof LegalTerminiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/annunci'
    | '/audit-log'
    | '/contacts'
    | '/galleria-foto'
    | '/home'
    | '/inventory'
    | '/platforms'
    | '/registro-corrispettivi'
    | '/reports'
    | '/settings'
    | '/legal/termini'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/annunci'
    | '/audit-log'
    | '/contacts'
    | '/galleria-foto'
    | '/home'
    | '/inventory'
    | '/platforms'
    | '/registro-corrispettivi'
    | '/reports'
    | '/settings'
    | '/legal/termini'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/annunci'
    | '/_authenticated/audit-log'
    | '/_authenticated/contacts'
    | '/_authenticated/galleria-foto'
    | '/_authenticated/home'
    | '/_authenticated/inventory'
    | '/_authenticated/platforms'
    | '/_authenticated/registro-corrispettivi'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/legal/termini'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  LegalTerminiRoute: typeof LegalTerminiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/termini': {
      id: '/legal/termini'
      path: '/legal/termini'
      fullPath: '/legal/termini'
      preLoaderRoute: typeof LegalTerminiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/registro-corrispettivi': {
      id: '/_authenticated/registro-corrispettivi'
      path: '/registro-corrispettivi'
      fullPath: '/registro-corrispettivi'
      preLoaderRoute: typeof AuthenticatedRegistroCorrispettiviRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platforms': {
      id: '/_authenticated/platforms'
      path: '/platforms'
      fullPath: '/platforms'
      preLoaderRoute: typeof AuthenticatedPlatformsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/galleria-foto': {
      id: '/_authenticated/galleria-foto'
      path: '/galleria-foto'
      fullPath: '/galleria-foto'
      preLoaderRoute: typeof AuthenticatedGalleriaFotoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit-log': {
      id: '/_authenticated/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuthenticatedAuditLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/annunci': {
      id: '/_authenticated/annunci'
      path: '/annunci'
      fullPath: '/annunci'
      preLoaderRoute: typeof AuthenticatedAnnunciRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnnunciRoute: typeof AuthenticatedAnnunciRoute
  AuthenticatedAuditLogRoute: typeof AuthenticatedAuditLogRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedGalleriaFotoRoute: typeof AuthenticatedGalleriaFotoRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedPlatformsRoute: typeof AuthenticatedPlatformsRoute
  AuthenticatedRegistroCorrispettiviRoute: typeof AuthenticatedRegistroCorrispettiviRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnnunciRoute: AuthenticatedAnnunciRoute,
  AuthenticatedAuditLogRoute: AuthenticatedAuditLogRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedGalleriaFotoRoute: AuthenticatedGalleriaFotoRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedPlatformsRoute: AuthenticatedPlatformsRoute,
  AuthenticatedRegistroCorrispettiviRoute:
    AuthenticatedRegistroCorrispettiviRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  LegalTerminiRoute: LegalTerminiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
